#!/usr/bin/env bash
##Run this from the package root! 
#`./scripts/bundle.sh`
cd src/ && \
rm DailyDrop.zip; \
zip -r9 DailyDrop.zip ./node_modules *.js sql postgres app constants && \
aws lambda update-function-code --function-name RDSApi --zip-file fileb://DailyDrop.zip
cd ..